-- Supabase SQL Editor veya CLI ile çalıştırın.

create table if not exists public.duty_pharmacies (
  id bigint generated by default as identity primary key,
  duty_date date not null,
  il text not null,
  ilce text not null default '',
  name text not null,
  address text not null,
  phone text not null,
  lat double precision,
  lng double precision,
  nobetecza_id bigint,
  synced_at timestamptz not null default now()
);

create index if not exists duty_pharmacies_duty_il_idx
  on public.duty_pharmacies (duty_date, il);

create index if not exists duty_pharmacies_il_ilce_idx
  on public.duty_pharmacies (il, ilce);

alter table public.duty_pharmacies enable row level security;

create policy "duty_pharmacies_select_anon"
  on public.duty_pharmacies for select
  to anon, authenticated
  using (true);

comment on table public.duty_pharmacies is 'Günlük nobetecza.com senkronu (service role yazar; anon okur).';
